### PR TITLE
Use explicit widths when defining protocol fields in messages

### PR DESCRIPTION
**Pull request by pprindeville**
Best practices for network programming is to use types from <stdint.h>
which have explicit numbers of bits.

### CODE REVIEW

**Comment by daveolson53** [comment]
Philip Prindeville <notifications@github.com> wrote:

> Best practices for network programming is to use types from
> which have explicit numbers of bits.
> 
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/jeroennijhof/pam_tacplus/pull/66
> 
> Commit Summary
> 
>   • Use explicit widths when defining protocol fields in messages
> 
> File Changes
> 
>   • M libtac/include/tacplus.h (94)
> 
> Patch Links:
> 
>   • https://github.com/jeroennijhof/pam_tacplus/pull/66.patch

This changes types from signed into to unsigned 32 bit int.  That's
a definite ABI change that will cause problems for strict compilers.
Whether the type should be signed or not in a purest sense, I'd
recommend not making that change.  Use int32_t instead.  It's
messy for people to change types for sign.  

The rest look good.


>   • https://github.com/jeroennijhof/pam_tacplus/pull/66.diff

Same signed int to unsigned 32 bit int issue here.

Dave Olson
olson@cumulusnetworks.com

**Comment by pprindeville** [comment]
> Use int32_t instead.  It's messy for people to change types for sign.

I'm looking at the spec where it says:

> seq_no
> 
>    This is the sequence number of the current packet for the current
>    session. The first TACACS+ packet in a session MUST have the sequence
>    number 1 and each subsequent packet will increment the sequence
>    number by one. Thus clients only send packets containing odd sequence
>    numbers, and TACACS+ daemons only send packets containing even
>    sequence numbers.
> 
>    The sequence number must never wrap i.e. if the sequence number 2^8-1
>    is ever reached, that session must terminate and be restarted with a
>    sequence number of 1.

and wondering if it makes sense to use negative numbers.  If "the first [...] packet in a session MUST have the sequence number 1 and each subsequent packet will increment the sequence by one" then that implies that there are no values less than one...  So definitely no negative numbers.

**Comment by daveolson53** [comment]
Philip Prindeville <notifications@github.com> wrote:

>     Use int32_t instead. It's messy for people to change types for sign.
> 
> I'm looking at the spec where it says:
> 
>     seq_no
> 
>     This is the sequence number of the current packet for the current
>     session. The first TACACS+ packet in a session MUST have the sequence
>     number 1 and each subsequent packet will increment the sequence
>     number by one. Thus clients only send packets containing odd sequence
>     numbers, and TACACS+ daemons only send packets containing even
>     sequence numbers.
> 
>     The sequence number must never wrap i.e. if the sequence number 2^8-1
>     is ever reached, that session must terminate and be restarted with a
>     sequence number of 1.
> 
> and wondering if it makes sense to use negative numbers. If "the first [...]
> packet in a session MUST have the sequence number 1 and each subsequent packet
> will increment the sequence by one" then that implies that there are no values
> less than one... So definitely no negative numbers.

Clearly with 32 bits we aren't going to wrap.  And in a pure world, we
should use unsigned, and avoid some potential issues.

But now it's a potentially messy change for users of the libtac library,
and I would strongly suggest not making it.  Even if the library version
bumps, it would likely be an issue for some users.

Dave Olson
olson@cumulusnetworks.com

**Comment by pprindeville** [comment]
> Clearly with 32 bits we aren't going to wrap.

Actually, if you're using Tacacs command accounting and running a lot of really hairy shell scripts, plus have connection re-use enabled (I have a patch for that too coming up), then you can easily wrap your seq_no space in a couple of hours on a high-end vRouter.

> Even if the library version bumps, it would likely be an issue for some users.

I understand that.  But there are other changes which will definitely require users to do at least some minor rewriting.  Bear with me while we get to those.

You'll notice, for instance, that there are globals like `tac_secret` which imply that you're only ever going to have one Tacacs+ session, or if you do have multiple Tacacs+ sessions, they all share the same secret.  That's broken, and I have a fix for that as well.

These things can't be fixed without breaking some backward compatibility.

**Comment by daveolson53** [comment]
Philip Prindeville <notifications@github.com> wrote:

>     Clearly with 32 bits we aren't going to wrap.
> 
> Actually, if you're using Tacacs command accounting and running a lot of really
> hairy shell scripts, plus have connection re-use enabled (I have a patch for
> that too coming up), then you can easily wrap your seq_no space in a couple of
> hours on a high-end vRouter.

I mean the sequence number goes out of range first.  At least that's
my experience.  So it's forced to wrap before that.

>     Even if the library version bumps, it would likely be an issue for some
>     users.
> 
> I understand that. But there are other changes which will definitely require
> users to do at least some minor rewriting. Bear with me while we get to those.

type changes tend to be much nastier and less mechanical.  libpam isn't
the only user of the library (at least for me).

> You'll notice, for instance, that there are globals like tac_secret which imply
> that you're only ever going to have one Tacacs+ session, or if you do have
> multiple Tacacs+ sessions, they all share the same secret. That's broken, and I
> have a fix for that as well.

Yes.  Someday that all needs to be fixed.  Along with persistent
conntections.

> These things can't be fixed without breaking some backward compatibility.

Agreed.  But let's not break things multiple times.

Dave Olson
olson@cumulusnetworks.com

**Comment by pprindeville** [comment]
> I mean the sequence number goes out of range first. At least that's my experience. So it's forced to wrap before that.

I don't know that a lot of servers enforce that check.  Seems a bit pointless, in any case.

> Agreed. But let's not break things multiple times.

Okay, but what about a "big bang" breakage?  Being serious here.

I've got some other changes which I'm [forward] porting that should be out in the next couple of days (well, by Wednesday at the latest) which will be fairly disruptive by necessity.

**Comment by daveolson53** [comment]
Philip Prindeville <notifications@github.com> wrote:

>     I mean the sequence number goes out of range first. At least that's my
>     experience. So it's forced to wrap before that.
> 
> I don't know that a lot of servers enforce that check. Seems a bit pointless,
> in any case.
> 
>     Agreed. But let's not break things multiple times.
> 
> Okay, but what about a "big bang" breakage? Being serious here.

I think that's mostly up to Jeroen.  I don't know how many users
of libtac there are.  I know I'm one, I've heard from a couple of
others.

> I've got some other changes which I'm [forward] porting that should be out in
> the next couple of days (well, by Wednesday at the latest) which will be fairly
> disruptive by necessity.

It might be worth talking about them in advance, to get some feedback.

Dave Olson
olson@cumulusnetworks.com

**Comment by pprindeville** [comment]
> It might be worth talking about them in advance, to get some feedback.

Okay, so here are the changes:

* redux of packet marshalling: formatting/parsing packets is distinct from sending/receiving packets (in case you want to provide your own I/O methods);
* add session params: create a session structure, and move things into that so that (a) globals like timeouts and secrets can be per-session/per-server, and (b) avoid an explosion of arguments being passed to methods (when the majority of parameters can be contained in the session object);
* add libevent support: if you're doing event-driven I/O, possibly across multiple sessions, then you can't use blocking methods like `tac_author_send()` because while we're waiting for a send on that session to complete, a read or read-timeout might be occurring on another session (note this preserves the original API);
* use constructor attribute to invoke `magic_init()` at startup rather than using the static flag hack;
* make the socket fd be a session parameter;
* add callback cookies into session;
* make TACDEBUG() be varargs so we don't need the ((args)) hack;

and other miscellaneous cleanup.

Obviously, the biggest change is moving parameters from globals into the `tac_session` which will be highly impactful and require an API major version bump.

**Comment by daveolson53** [comment]
Philip Prindeville <notifications@github.com> wrote:

>     It might be worth talking about them in advance, to get some feedback.
> 
> Okay, so here are the changes:
> 
>   • redux of packet marshalling: formatting/parsing packets is distinct from
>     sending/receiving packets (in case you want to provide your own I/O
>     methods);
>   • add session params: create a session structure, and move things into that
>     so that (a) globals like timeouts and secrets can be per-session/
>     per-server, and (b) avoid an explosion of arguments being passed to methods
>     (when the majority of parameters can be contained in the session object);
>   • add libevent support: if you're doing event-driven I/O, possibly across
>     multiple sessions, then you can't use blocking methods like tac_author_send
>     () because while we're waiting for a send on that session to complete, a
>     read or read-timeout might be occurring on another session (note this
>     preserves the original API);
>   • use constructor attribute to invoke magic_init() at startup rather than
>     using the static flag hack;
>   • make the socket fd be a session parameter;
>   • add callback cookies into session;
>   • make TACDEBUG() be varargs so we don't need the ((args)) hack;
> 
> and other miscellaneous cleanup.
> 
> Obviously, the biggest change is moving parameters from globals into the
> tac_session which will be highly impactful and require an API major version
> bump.

To me, these all sound like good things, and I should be able to use
some of this in my extended tacacs client code (which I'm still working
on getting on github, other work stuff is slowing me down).

What has inspired you to do this significant work?  Are you using the
new code in a product, or a new app?

Dave Olson
olson@cumulusnetworks.com

**Comment by pprindeville** [comment]
> What has inspired you to do this significant work? Are you using the new code in a product, or a new app?

At Brocade I was working on a Tacacs+ proxy daemon for SSSD which required being able to talk to multiple servers at once (for redundancy) and the daemon itself was event-driven.

So the work has already been done.  It just needs to be ported to HEAD, which I'm doing now.

**Comment by pprindeville** [comment]
> So the work has already been done. It just needs to be ported to HEAD, which I'm doing now.

On the subject of that, porting the patches is a lot trickier than I thought it would be... the commit 87a678a changed a lot of the indent so most of the patches are being rejected and I'm having to redo them (about 800 lines) by hand.

**Comment by acooks** [comment]
If we can find out how the reformatting of 87a678a was done (assuming it was programmatic), my approach for rebasing our patches would be:

1. revert  87a678a
2. apply the patches
3. reapply the reformatting transform
4. reset git HEAD to before the revert
5. restage & commit each patch.

**Comment by pprindeville** [comment]
@acooks: I hand applied the diffs (which wasn't without peril... I introduced the damage that's fixed in PR #76).  Hopefully the succeeding patches will apply more easily (they should... they're less extensive for the most part).

**Review by kravietz — APPROVED** [review]

**Review by kravietz — APPROVED** [review]

**Comment by kravietz** [comment]
Continued in https://github.com/kravietz/pam_tacplus/pull/177

**Pull request closed without merging**
